select PC.PC_CUENTA_CB, 
       TP.TP_NUMERO,
       TA.TACB_CUITCUIL,
	   TP.TP_NOMBRE,
	   PC.PC_ESTITULAR_CB ,
	   nm.NVDM_RECHAZO,
	   cea.CEA_DESCRIPCION
 from NOVEDAD_MODIFICACION NM INNER JOIN MODIFICACIONES_TARJETAS_PREPAGAS MT ON MT.MTP_ID = NM.MTP_ID
                              INNER JOIN TARJETA_PREPAGA_CB TP ON MT.TP_ID = TP.TP_ID
							  INNER JOIN TITULAR_ADICIONAL TA ON TP.TACB_ID = TA.TACB_ID
							  INNER JOIN PERSONA_CUENTA PC ON TA.TACB_ID = PC.TACB_ID 
							  INNER JOIN CODIGO_ERROR_ARCHIVO_ALTAS CEA ON CEA.CEA_CODIGO = right(nm.NVDM_RECHAZO,3)
where NVDM_NRO_FORMULARIO in (564,566) and NVDM_RECHAZO is not null
