
DECLARE @vMensaje VARCHAR(200)

SET NOEXEC OFF

IF @@SERVERNAME <> 'B1842ZACS0081' 
  BEGIN
    SELECT '¡¡ESTE NO ES EL AMBIENTE DE TESTEO!!' AS MENSAJE, 'B1842ZACS0081' SERVIDOR_DONDE_DEBE_EJECUTARSE, @@SERVERNAME SERVIDOR_DONDE_SE_EJECUTO
    PRINT  '¡¡ESTE NO ES EL AMBIENTE DE TESTEO!! (Servidor donde debe ejecutarse: B1842ZACS0081 | Servidor donde se ejecutó: ' + @@SERVERNAME + ')'
    SET NOEXEC ON
  END
ELSE    
  PRINT ' - AMBIENTE: TESTEO (' + @@SERVERNAME + ')'


