select FS.NOMBRE       SECCION,
       FM.NOMBRE       MENU_NOMBRE,
       FM.CONTROLADOR  MENU_CONTROLADOR,
       FM.ACCION       MENU_ACCION,
       FC.ACCION       MENU_CONTROLADOR_ACCION,
       FC.CONTROLADOR  MENU_CONTROLADOR_CONTROLADOR
  FROM FW_SECCIONES FS INNER JOIN FW_MENU FM INNER JOIN FW_MENU_CONTROLADOR FC 
                                             ON FM.ID_MENU = FC.MENU_ID
                       ON FS.SECCION_ID = FM.SECCION
ORDER BY FS.NOMBRE,
         FM.NOMBRE,
         FC.ACCION
    
