
  declare @cmd varchar(100),
          @result int, 
		  @MascaraArchivos varchar(50) =  'CONS____.___' ,
		  @FILAS_TOTAL INT = 0,
		  @FILA_ACTUAL INT = 1,
		  @pNOMBRE_ARCHIVO VARCHAR (50),
		  @sSql VARCHAR(MAX),
		  @pPATH VARCHAR(100)
  SET @pPATH =  '\\' + @@SERVERNAME + '\CABAL_STP\in\'  
  SET @CMD= 'DIR / B '+ @pPATH 
  DELETE TEMP_RECEPCION_CONSUMO_PRUEBA
  
  IF OBJECT_ID('tempdb..#CMD') IS NOT NULL DROP TABLE #CMD CREATE TABLE #CMD (Line VARCHAR(512))  
  IF OBJECT_ID('tempdb..#CMD_ID') IS NOT NULL DROP TABLE #CMD_ID CREATE TABLE #CMD_ID (ID INT IDENTITY (1,1) NOT NULL, Line VARCHAR(512))  
    
  INSERT INTO #CMD  EXECUTE @Result = MASTER..XP_CMDSHELL @cmd  

  DELETE #CMD WHERE LINE NOT LIKE @MASCARAARCHIVOS OR LINE IS NULL
  
  INSERT INTO #CMD_ID (LINE) SELECT LINE FROM #CMD

  SET @FILAS_TOTAL = (SELECT COUNT(*) FROM #CMD_ID)
  --SET @FILA_ACTUAL = 17

  WHILE @FILAS_TOTAL >= @FILA_ACTUAL
   BEGIN 
     SET @pNOMBRE_ARCHIVO = (SELECT RTRIM(LTRIM(Line)) FROM #CMD_ID WHERE ID =  @FILA_ACTUAL)

     set @sSql = 'INSERT INTO  '+DB_NAME()+'.dbo.TEMP_RECEPCION_CONSUMO_PRUEBA(RC_LINEA, RC_ARCHIVO) '          
     set @sSql =  @sSql  + 'SELECT linea,'+ ''''  + @pNOMBRE_ARCHIVO + ''''  + ' FROM OPENROWSET( BULK '+''''+ @pPATH +@pNOMBRE_ARCHIVO+''''+', FORMATFILE = '+''''+ @pPATH +'FMT\CONS.FMT'+''''+', MAXERRORS=0) AS ARCH  '          
          
     execute (@sSql)        
	 
	 SET @FILA_ACTUAL = @FILA_ACTUAL + 1 

   END

   SELECT  (CONVERT(NUMERIC(13,2), SUBSTRING(RC_LINEA, 110,9)))   /100
     FROM TEMP_RECEPCION_CONSUMO_PRUEBA
   ORDER BY 1